CREATE TABLE IF NOT EXISTS parties (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
reunion_id BIGINT,
contrat_id BIGINT,
preneur_id BIGINT,
appel_id BIGINT,
mort_id BIGINT,
est_fait BOOLEAN,
points INTEGER,
petit_au_bout_id BIGINT,
chelem BOOLEAN,
capot BOOLEAN,
CONSTRAINT pk_parties PRIMARY KEY (id));